version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: school
      POSTGRES_PASSWORD: schoolpass
      POSTGRES_DB: schooldb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  db-data:
